name: Test Python package

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project and dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install .
      - name: Lint with flake8
        run: |
          flake8 wayfarer --max-line-length=160
          flake8 scripts --max-line-length=160
          flake8 --ignore=E501,E121,E122,E123,E126,E127,E128 tests
      - name: Test with pytest
        run: |
          pytest --cov wayfarer --cov-report= tests/
      - name: Upload coverage data to coveralls.io
        run: |
          coveralls
        env:
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build wheel and source distributions
        run: |
          pip install wheel
          pip install build
          python -m build --wheel
          python -m build --sdist

  # see https://github.com/marketplace/actions/coveralls-github-action
  # we can't use coveralls-github-action as it doesn't support xml output
  # see https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to PyPI
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
