name: Test Python package

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project and dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install .
      - name: Lint with flake8
        run: |
          flake8 wayfarer --max-line-length=160
          flake8 scripts --max-line-length=160
          flake8 --ignore=E501,E121,E122,E123,E126,E127,E128 tests
      - name: Test with pytest
        run: |
          pytest --cov wayfarer --cov-report= tests/
      - name: Upload coverage data to coveralls.io
        run: |
          coveralls
        if: ${{ matrix.python-version != 2.7 }}
        env:
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
          # COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # see https://github.com/marketplace/actions/coveralls-github-action
  # we can't use coveralls-github-action as it doesn't support xml output
  # see https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
